### ISSUE TITLE
Difference between tr-projections.tsv tr-projections2.tsv

### ISSUE THREAD

**Issue by frankier** [Helsinki-NLP/XED#1]
Thanks for making this dataset. What is the difference between `tr-projections.tsv` and `tr-projections2.tsv`? Which should be preferred?

**Comment by esohman** [comment]
_tr-projections2.tsv_ is the correct one. I have removed _tr-projections.tsv_ to avoid confusion.

**Comment by frankier** [comment]
Okay! However, now looking again I notice that tr-projections2.tsv is the only file with a header. Would it be possible to remove it for consistency?

**Comment by esohman** [comment]
Apologies for the long wait. The header has been removed.
