### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by frankier** [Helsinki-NLP/XED#3]
The README states:

>Metadata can be found in the metadata file and the projection "pairs" files. Access to detailed metadata can be found on the OPUS website.

Are these files included in the repo? Where are they? It would be nice if there were keys available which could be used to easily find the source sentence in OpenSubtitles.

**Comment by esohman** [comment]
The metadata can be found under subtitle-retrieval/students. The metadata for each language pair can be found in its corresponding _pairs.txt_ file and for the student annotations in the _student_annotations.csv_ file. The OpenSubtitles subtitle IDs from these files can then be used to access metadata on OPUS.

**Comment by frankier** [comment]
Okay that's useful for finding which subset has been annotated, although it doesn't seem to be easy to go from the annotations back to the metadata without looking at the sentences themselves. The reason I asked is because I'm looking at improving the integration of XED into huggingface datasets and I noticed they're adding sentence ids to OpenSubtitles itself https://github.com/huggingface/datasets/issues/1844 -- so I thought it might be nice to add the ids to the XED dataset too. On the other hand, if it's not already easily possible, then it might not be so important.
