### ISSUE TITLE
Issue in Danish data

### ISSUE THREAD

**Issue by ruitedk6** [Helsinki-NLP/XED#4]
I wanted to use your Danish data, but I saw that there is an issue with the letter "l" (lowercase "L"), which is written as "I" (uppercase "i") in da-projections.tsv. I didn't see this until I saw the data in a monospace font. I know this can be easily fixed via regex but just wanted to let you know.

Here an example:

```
Written: "Min bedste Ianding hidtiI."
Should be: "Min bedste landing hidtil."
```

**Comment by esohman** [comment]
Thanks for letting me know. I believe this is an issue based on the original open subtitles data and applies to multiple languages. We have manually fixed many such issues, but if you find any more, you can always submit a pull request. I have now fixed all these issues in the Danish data.
